name: malibu_orange
description: descriptions
publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.15
  firebase_analytics: ^9.1.7
  flutterfire_ui: ^0.4.0+5
  cloud_functions: ^3.2.14
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  google_fonts: ^2.3.2
  # Ads
  google_mobile_ads: ^1.2.0
  flutter_overboard: ^3.1.1
  uuid: ^3.0.6
  flutter_native_splash: ^2.1.6
  go_router: ^3.1.0
  # Testing
  mockito: ^5.2.0
  shared_preferences: ^2.0.15
  rive: ^0.9.0
  audioplayers: ^1.0.1
  in_app_review: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
flutter_icons:
  android: true
  image_path: "assets/images/app-icon.png"
flutter_native_splash:
  # color: "#826599"
  image: "assets/images/app-icon.png"
