name: malibu_orange
description: descriptions
publish_to: 'none'
version: 1.0.2+6
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_analytics: ^9.1.10
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  syncfusion_flutter_gauges: ^20.2.50
  # Ads
  google_mobile_ads: ^1.3.0
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.10.0
  go_router: ^3.1.0
  # Testing
  mockito: ^5.2.0
  shared_preferences: ^2.0.15
  environment_sensors: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3
  json_serializable: ^6.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
flutter_native_splash:
  color: "#fce897"
  image: "assets/images/ic_launcher.png"
